### PR TITLE
Fix broken layout in mobile devices

### PR DESCRIPTION
**Pull request by vikrant0017**
Fix the alignment of the of the user info section in the profile page for mobile devices

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
On it, I'll review the changes right away.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Looks like this code change didn’t fix the problem. Can you take a second look?

**Review by vanessa-cooper — APPROVED** [review]
Nailed it! Excellent job @vikrant0017! You can now merge the PR.

**Comment by vikrant0017** [comment]
This issue has been resolved now.
ss_fix_profile_layout

**Pull request merged**
